### ISSUE TITLE
Sample scene?

### ISSUE THREAD

**Issue by andybak** [mlavik1/UnityVolumeRendering#1]
I'll have a go at figuring out what scripts go where but (in lieu of docs) a sample scene already set up would be great.

Looks interesting by the way!

**Comment by mlavik1** [comment]
@andybak Thank you for the feedback!

If you open "TestScene.unity" you can import a volume by selecting "Volume Rendering"-> "Load dataset" in the menu bar.
I would recommend the "manix.dat" dataset in the "DataFiles"-folder. The default import settings should be Ok. You can edit transfer functions from the same menu bar dropdown.
![bilde](https://user-images.githubusercontent.com/6906872/55545501-9e8f8100-56cd-11e9-9429-7cb1b50fdd59.png)

I have only tested with Unity 2018.1.5, I suppose it should work with newer versions as well.

I'll start adding some more documentation when I'm home from work. It's stil work in progress, so sorry for the lack of information :) 
Thanks for reminding me!

**Comment by mlavik1** [comment]
@andybak I have updated the readme now: https://github.com/mlavik1/UnityVolumeRendering/blob/master/README.md

Thanks for the feedback!
I realised there is still lots of things left to do :)
