### ISSUE TITLE
cannot import .raw data

### ISSUE THREAD

**Issue by boringfish** [mlavik1/UnityVolumeRendering#103]
Hi, Thanks for your sharing.
I'm trying to use different samples to show their rendering results. And I find some DICOM datasets from http://ngavrilov.ru/invols/index.php?id=Download
The problem is that these datasets are raw datasets and when I try to import them with **Load raw dataset**,  it cannot work. 
![image](https://user-images.githubusercontent.com/32609638/181905215-70fbd0ba-9508-4a6b-8202-676118226352.png)

Could you tell me what the problem is and how I can use these datasets?
Thanks for your helping.

**Comment by mlavik1** [comment]
Hi! Sorry for the late reply. I've been away on holiday, and then moving :) 
So for the RAW importer to be able to import a dataset, you need to specify how it should read it (either though that dialogue in your screenshot, or though an .ini file).

You need to fill inn:
- Dimension: (manix appears to be 256x256x277?)
- Bytes to skip: some RAW datasets have a header where some info is stored. This would be the size of that header).
- Data format: What the values are. Typically 8 or 16 bit ints, or floats.. Here it says "12 bit though".. Do you know anything about the format?
- Endianness (typically little endian)
