### ISSUE TITLE
Get no normalized density values of 3d texture? For Window Settings

### ISSUE THREAD

**Issue by MusoAga** [mlavik1/UnityVolumeRendering#13]
Thanks mlavik. That is I was talking about #11. Thats a nice step, to see the shown range directly without normilzed values. My problem is, the shader still uses the normilized values. I do not know if anyone needs this as a featured. Would it be technically possible to get the density as unormalized value in the shader? I tried, but could not solve it. I think the shader uses the alpha value of the current pixel on the 3D texture, which can only have a alpha between 0-1. I want to implement this in the shader:

```
if (x <= c - 0.5 - (w-1) /2), then y = ymin
else if (x > c - 0.5 + (w-1) /2), then y = ymax
else y = ((x - (c - 0.5)) / (w-1) + 0.5) * (ymax- ymin) + ymin
```

Where:
```
c = WindowCenter 
w = WindowWidth
x = returned Density (for example 2154)
y = (Color or Alpha Value)
```

Currently the shader shows everything withing Max and Min. The above linear function depends on Window Width/Center, not directly on Min and Max. 

Please correct me if I am wrong :D

Actually it would be also possible to do this with the normalized values, but I think it is noticeably more performant to make this with intergers and avoid to normilize the WindowCenter and WindowWidth as well.

Here is an example to this feature: [RadiAnt ](https://www.radiantviewer.com/dicom-viewer-manual/changing-color-and-opacity.html)

I tried it with a Custom Render Mode, but I got this Image. I do not really now how to map the WindowSettings to the normilized Values. My goal is, to setup some templates with fixed WindowSettings, because I want to show the Series in VR. I want to avoid dynamic changes with slider, to make the VR environment more comfortable.
![grafik](https://user-images.githubusercontent.com/12189192/74930339-a89d9980-53dd-11ea-8ad6-4dc6022c35e1.png)

**Comment by mlavik1** [comment]
Hi again!

Hmm.. so I read about the window centre/width.
If I understand it right, then ymin and ymax are the output values, and are usually a grayscale colour value, right?
If so, it makes sense for slice rendering. In that case the output value can simply be used as a grayscale colour value.
However, what should the output be used for in 3D? To modify the alpha value, maybe?

Anyway, I think I'd like to keep the data values and TF values normalised by default. If not it won't be possible to use the same TF texture on several data sets (unless the TF texture is normalised, and we convert from real value to normalised when applying the TF..). You are of course free to change that in your fork, but it should also be possible to do this with normalised data values.
You can use these functions for converting between normalised/real data values:

            float AbsToNorm(float value)
            {
                const float minval = -1000.0f;
                const float maxval = 3000.0f;
                return ((float)value - minval) / (maxval - minval);
            }

            float NormToAbs(float value)
            {
                const float minval = -1000.0f;
                const float maxval = 3000.0f;
                return lerp(minval, maxval, value);
            }
This could probably be useful for others, so I can merge the above functions into master (and also pass the min/max values to the shader, so you don't have to hard-code them).

And the function that applies the window could then look like this:

            float ApplyWindow(float x)
            {
                float c = 1000.0f;
                float w = 200.0f;
                float ymin = 0.0f; // black
                float ymax = 1.0f; // white
                if (x <= c - 0.5 - (w-1) /2)
                    return ymin;
                else if (x > c - 0.5 + (w-1) /2)
                    return ymax;
                else
                    return ((x - (c - 0.5)) / (w-1) + 0.5) * (ymax- ymin) + ymin;
            }

And you can call it like this: `ApplyWindow(NormToAbs(density))`

I'm not sure how you want to use the output though. In surface rendering mode ("frag_surf" shader) you could do something like this: `col.rgb = float3(1.0f, 1.0f, 1.0f) * ApplyWindow(NormToAbs(density));`
Or you could maybe use it to set the alpha value in the direct volume rendering shader? ("frag_dvr")

I'm sorry for my lack of knowledge about DICOM, but I hope this was of some help.
Again: after some relearch I have the impression that such windows are mostly used for (2D) slice rendering, and I'm not entirely sure how it would be used in 3D (and what the output should be used for), so please let me know if you have some clues :slightly_smiling_face:

**Comment by MusoAga** [comment]
Thanks @mlavik1! İ will try that out and give later a report. Actually İ also thought that the Window settings only can be applied to slices. But İ many applications it is also possible to apply this to 3D. These also only make sense if you have grayscales, so DİCOM data with the tag Photometric Interpretation: Monochrome 1/2.

The output value is not defined by the standard İ think. Thats why İ will experimente with this. İn 2D slices it corresponds to Brightness/Contrast settings. 

İf you say this would be hard to work with unnormilezed values, then İ will try your way. 

İf you want you can download the RadiAnt Viewer and try the feature with 3D.

İf this will not work quickly, İ will just leave it 😁

**Comment by mlavik1** [comment]
Hmm.. yes. That's my understanding as well. 
I guess it could be used to modify the alpha value in direct volume rendering (3D) as well, in that case it should be possible to achieve the same result using normal transfer functions.

Thanks! I'll give RadiAnt a try 🙂 
btw, you wrote "I want to show the Series in VR". Feel free to let me know if you get some performance issues. I haven't tested it in VR yet, but if you get poor performance you might want to adjust NUM_STEPS or just add "[unroll]" before the foor loops (that makes shader compilation really slow though).
I'll also try getting rid of that huge "if"-check in "frag_dvr" 😂

**Comment by MusoAga** [comment]
Nah I tried it, but it just gives me 2D Slice on both sides of the cubes. I am sure it _could_ work, but for now I will just leave it :D For now I will use the TF. 

![grafik](https://user-images.githubusercontent.com/12189192/75021619-fb865800-5494-11ea-98eb-8bfe1eff8148.png)
![grafik](https://user-images.githubusercontent.com/12189192/75021641-0640ed00-5495-11ea-8d96-cebed05be408.png)
![grafik](https://user-images.githubusercontent.com/12189192/75022087-c0d0ef80-5495-11ea-9254-6f21457e46a2.png)


Yes, I already had issues with VR :D Like you said, I had to decrease the NUM_STEPS to like 256 or 512. And also I compress the data of the DICOM with bilinear interpolation and merging the pixel values of every 2 Slices with a simple arithmetic mean. With this I have a good 3D image, which runs ok in VR. I will try the [unroll] :D

**Comment by mlavik1** [comment]
Ok, I see. Thanks for sharing your results!

Oh seems like you already figured it out 🙂 
"[unroll]" might make Unity freeze forever, but I'll see if I can get rid of that branch. That should help performance, and maybe help reduce the compilation time when using "[unroll]" as well. I'll let you know if I have any luck with that!

**Comment by mlavik1** [comment]
**Update about the performance issues you had:**
If you are using 1D transfer functions and direct volume rendering mode (the default one), then you should be able to get a lot better performance by pulling latest from master.
See https://github.com/mlavik1/UnityVolumeRendering/pull/16.
I have tested with D3D11 (Windows) and OpenGL (Linux), and got more than 50% better performance on both (Windows: 21FPS->68FPS).
Isosurface render mode and 2D trasnfer functions are still slow though.

Hope it helps for VR 🙂

**Comment by MusoAga** [comment]
Thank your very much ! I will try it out :)
