### ISSUE TITLE
Volume raycaster

### ISSUE THREAD

**Issue by mlavik1** [mlavik1/UnityVolumeRendering#140]
Implement functionality for raycasting volumetric dataset (in C#) to find intersections.
Requested by @Karthikarc115

**Comment by mlavik1** [comment]
Hi @Karthikarc115

I've implemented a basic raycaster now, and pushed to the [volume-raycast branch](https://github.com/mlavik1/UnityVolumeRendering/tree/volume-raycast).
See the [DistanceMeasureTest.cs](https://github.com/mlavik1/UnityVolumeRendering/blob/volume-raycast/Assets/Scripts/SampleScene/DistanceMeasureTest.cs) script for an example.
You can do the raycasts like this:
```csharp
if (Input.GetMouseButtonDown(0))
{
    Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
    VolumeRaycaster raycaster = new VolumeRaycaster();
    RaycastHit hit;
    if (raycaster.RaycastScene(ray, out hit))
    {
        //Debug.DrawLine(ray.origin, hit.point, Color.red, 10.0f, true);
        lineRenderer.SetPosition(0, lineRenderer.GetPosition(1));
        lineRenderer.SetPosition(1, hit.point);
        float distance = Vector3.Distance(lineRenderer.GetPosition(0), lineRenderer.GetPosition(1));
        Debug.Log($"Distance: {distance}");
    }
}
```

The line renderer looks like this:
![image](https://user-images.githubusercontent.com/6906872/207699527-922a3d11-231d-4103-a0dd-62a5d53ba78b.png)
You'll probably want to use a different material though. This one had "depth test" enabled, so it will be hidden behind the dataset. So you might want to use a shader that has [disabled Z test](https://docs.unity3d.com/Manual/SL-ZTest.html).

**Comment by mlavik1** [comment]
Let me know if this is what you want.
By the way, the raycasts don't handle cross section planes/boxes yet.. So they will hit the first point that is not invisibile (based on visibility window and transfer function).

Here's a visualisation of the rays:
![image](https://user-images.githubusercontent.com/6906872/207700230-38da65b6-913c-470a-bfa0-0c7a14d346cc.png)

**Comment by Karthikarc115** [comment]
Hai Matias volume raycaster assembly is missing in this files

**Comment by mlavik1** [comment]
Sorry, I've pushed the file snow!

**Comment by Karthikarc115** [comment]
> Sorry, I've pushed the files now!

okay I'll try it

**Comment by mlavik1** [comment]
**Update:** I've just updated the branch. The raycaster now takes cross section plane/box into account as well.
And the distance measure tool in the sample scene shows the distance.

![image](https://user-images.githubusercontent.com/6906872/207924609-b4060b0f-488f-4ad3-839a-f6f195f10bef.png)

**Comment by mlavik1** [comment]
![image](https://user-images.githubusercontent.com/6906872/207925274-7b8309cd-8658-4c3b-b07d-a2a438425edc.png)
![image](https://user-images.githubusercontent.com/6906872/207925439-b46f5af8-c16f-4253-aafc-5b4994a0e7b3.png)

**Comment by Karthikarc115** [comment]
> **Update:** I've just updated the branch. The raycaster now takes cross section plane/box into account as well.
> And the distance measure tool in the sample scene shows the distance.
> 
> ![image](https://user-images.githubusercontent.com/6906872/207924609-b4060b0f-488f-4ad3-839a-f6f195f10bef.png)
> 

Thank you for your kind support I'll try it in my project

**Comment by mlavik1** [comment]
> > **Update:** I've just updated the branch. The raycaster now takes cross section plane/box into account as well.
> > And the distance measure tool in the sample scene shows the distance.
> > ![image](https://user-images.githubusercontent.com/6906872/207924609-b4060b0f-488f-4ad3-839a-f6f195f10bef.png)
> 
> Thank you for your kind support I'll try it in my project

Great, please let me know if it works for you :)

**Comment by Karthikarc115** [comment]
> > > **Update:** I've just updated the branch. The raycaster now takes cross section plane/box into account as well.
> > > And the distance measure tool in the sample scene shows the distance.
> > > ![image](https://user-images.githubusercontent.com/6906872/207924609-b4060b0f-488f-4ad3-839a-f6f195f10bef.png)
> > 
> > 
> > Thank you for your kind support I'll try it in my project
> 
> Great, please let me know if it works for you :)

sure I'll let you know

**Comment by Karthikarc115** [comment]
hai Matias iam trying to implement this functionality but iam not getting output like this is there any solution for this
![radiant-viewer-preview (1)](https://user-images.githubusercontent.com/99883381/208023210-057a82a4-b023-486f-bc9d-fefd87eaf181.jpg)

**Comment by mlavik1** [comment]
That's a screenshot of RadiAnt dicom viewer? Maybe you uploaded the wrong screenshot? 🙂

**Comment by mlavik1** [comment]
Ah sorry, I misunderstood. You want to measure distances on a 2D slice View like that in RadiAnt? I'll see if I can add that too 🙂
There is a slice renderer already, but it doesn't display distances.

**Comment by Karthikarc115** [comment]
> Ah sorry, I misunderstood. You want to measure distances on a 2D slice View like that in RadiAnt? I'll see if I can add that too 🙂
> There is a slice renderer already, but it doesn't display distances. 

Okay,iam also trying to implement that let's see how it works

**Comment by mlavik1** [comment]
I've merged the volume raycaster feature in now, and made a new issue for your request: #145 
I'll look at that next.
