### ISSUE TITLE
Issues with single pass VR rendering.

### ISSUE THREAD

**Issue by QY0911** [mlavik1/UnityVolumeRendering#147]
Hi All,
I'm facing the same problem switching to unity2020. I already edited the macros as @stefano-pittalis was suggesting but it is still not working. Using XRSDK I don't have anymore the option to choose btw single or multi pass rendering. What am I missing? Thanks!!
Here the code for the SliceRenderingShader.shader

// Upgrade NOTE: replaced 'UNITY_INSTANCE_ID' with 'UNITY_VERTEX_INPUT_INSTANCE_ID'

// Upgrade NOTE: replaced '_Object2World' with 'unity_ObjectToWorld'

Shader "VolumeRendering/SliceRenderingShader"
{
    Properties
    {
        _DataTex("Data Texture (Generated)", 3D) = "" {}
        _TFTex("Transfer Function Texture", 2D) = "white" {}
    }
    SubShader
    {
        Tags { "Queue" = "Transparent" }
        LOD 100
        Cull Off

        Pass
        {
            CGPROGRAM
            #pragma vertex vert
            #pragma fragment frag
            
            #include "UnityCG.cginc"

            struct appdata
            {
                float4 vertex : POSITION;
                float2 uv : TEXCOORD0;
                UNITY_VERTEX_INPUT_INSTANCE_ID   //added
            };

            struct v2f
            {
                float2 uv : TEXCOORD0;
                float4 vertex : SV_POSITION;
                float4 relVert : TEXCOORD1;
                UNITY_VERTEX_INPUT_INSTANCE_ID   //added
                UNITY_VERTEX_OUTPUT_STEREO  //added
            };

            sampler3D _DataTex;
            sampler2D _TFTex;
            uniform float4x4 _parentInverseMat;
            uniform float4x4 _planeMat;

            v2f vert (appdata v)
            {
                v2f o;
                float3 vert = float3(-v.uv.x, 0.0f, -v.uv.y) + float3(0.5f, 0.0f, 0.5f);
                vert = mul(_planeMat, float4(vert, 1.0f));
                //o.vertex = mul(UNITY_MATRIX_VP, float4(vert, 1.0f));
                //added-----------------
                UNITY_SETUP_INSTANCE_ID(v);         
                UNITY_TRANSFER_INSTANCE_ID(v, o);
                UNITY_INITIALIZE_VERTEX_OUTPUT_STEREO(o);
                //added---------------------
                o.vertex = UnityObjectToClipPos(v.vertex);;
                o.relVert = mul(_parentInverseMat, float4(vert, 1.0f));
                o.uv = v.uv;
                return o;
            }
            
            UNITY_DECLARE_SCREENSPACE_TEXTURE(_MainTex);

            fixed4 frag (v2f i) : SV_Target
            {
                UNITY_SETUP_INSTANCE_ID(i); //added
                float3 dataCoord = i.relVert +float3(0.5f, 0.5f, 0.5f);
                float dataVal = tex3D(_DataTex, dataCoord);
                float4 col = tex2D(_TFTex, float2(dataVal, 0.0f));
                col.a = 1.0f;

                return col;
            }
            ENDCG
        }
    }
}

_Originally posted by @chiarapalu in https://github.com/mlavik1/UnityVolumeRendering/issues/54#issuecomment-919320738_

**Comment by mlavik1** [comment]
I still don't have a VR headset to test with, so I can't help much I'm afraid (hoping to get one soon though!).
But @karstennoe suggested a similar fix in #136 (even posted a diff, based on a more recent version of the shader).
Does that maybe work for you?

And I see the documentation for XRSDK mentioning ["two-pass stereo rendering"](https://docs.unity3d.com/Manual/xrsdk-display.html) , but are you sure there is no setting for enabling that?

**Comment by mlavik1** [comment]
Closing this now since the PR has been merged.
Please re-open or create a new issue if you still have the problem. I would also appreciate if you let me know if it works :)
