### ISSUE TITLE
Changing Intensity by pressing scroll button

### ISSUE THREAD

**Issue by Karthikarc115** [mlavik1/UnityVolumeRendering#153]
Hai Matias,

I have a doubt regarding the intensity changing of 3d volume in visibility window through pressing and moving scroll button in mouse rather through the visibility window horizontal silder, I tried to get it done but failed.

Also I have a doubt regarding the Anterior posterior marking inside the editor when we load and rotate the 3d volume,any help would be appreciated
![Screenshot (23)](https://user-images.githubusercontent.com/99883381/212853349-37b7138b-d431-4ed8-803b-71c74c20fd0c.png)

**Comment by mlavik1** [comment]
Hi,
I'm not sure if I understand what you mean. Could you maybe post some pictures from the Unity project to show which window you mean, and explain what you want to do? :) Thanks!

**Comment by Karthikarc115** [comment]
i need to do this visibility window horizontal slider function in mouse scroolwheel,fo that i tried to implement a if condition with if (Input.GetAxis("Mouse ScrollWheel") < 0) {} in this following function

// Visibility window
                GUILayout.Label("Visibility window (min - max visible values)");
                GUILayout.BeginHorizontal();
                Vector2 visibilityWindow = targetObject.GetVisibilityWindow();
                GUILayout.Label("min:");
                visibilityWindow.x = GUILayout.HorizontalSlider(visibilityWindow.x, 0.0f, visibilityWindow.y, GUILayout.Width(150.0f));
                GUILayout.Label("max:");
                visibilityWindow.y = GUILayout.HorizontalSlider(visibilityWindow.y, visibilityWindow.x, 1.0f, GUILayout.Width(150.0f));
                targetObject.SetVisibilityWindow(visibilityWindow);
                GUILayout.EndHorizontal();

inside EditVolumeGUI.cs code


![1](https://user-images.githubusercontent.com/99883381/213077943-87416507-3850-4ba1-850d-9b5c6d53d506.PNG)
![2](https://user-images.githubusercontent.com/99883381/213077956-c9fdfa07-7274-4f75-8f0f-c50570fe9a22.PNG)
![3](https://user-images.githubusercontent.com/99883381/213077960-41a35f00-be02-4ed2-ad3f-b98e9b1655c0.PNG)

**Comment by mlavik1** [comment]
So I don't think you'll get `Input.GetAxis` to work inside of an `OnGUI` call. I think your only option would be to use [Event.current](https://docs.unity3d.com/ScriptReference/Event-current.html), but that could still be hard to get right.
Could you instead create a new MonoBehaviour script and attach it to some object as a Component, and then do it inside the `Update` function? Then you should be able to use `Input.GetAxis`.
To get the VolumeRenderedObject (the `targetObject` variable in the code you attached) you can simply do:
```csharp
VolumeRenderedObject targetObject = GameObject.FindObjectOfType<VolumeRenderedObject>();
```

**Comment by Karthikarc115** [comment]
> So I don't think you'll get `Input.GetAxis` to work inside of an `OnGUI` call. I think your only option would be to use [Event.current](https://docs.unity3d.com/ScriptReference/Event-current.html), but that could still be hard to get right. Could you instead create a new MonoBehaviour script and attach it to some object as a Component, and then do it inside the `Update` function? Then you should be able to use `Input.GetAxis`. To get the VolumeRenderedObject (the `targetObject` variable in the code you attached) you can simply do:
> 
> ```cs
> VolumeRenderedObject targetObject = GameObject.FindObjectOfType<VolumeRenderedObject>();
> ```
> 
> See here for an example of using `Input.GetAxis` inside of `Update`: https://docs.unity3d.com/ScriptReference/Input.GetAxis.html

sure i'll try

**Comment by mlavik1** [comment]
Mind if I close this issue, or do you have any more questions regarding it? :)
