### ISSUE TITLE
Webgl FileBrowser issue

### ISSUE THREAD

**Issue by Karthikarc115** [mlavik1/UnityVolumeRendering#156]
Hai Matias,

I've tried to develop a method for file uploading in webgl, but I'm unsure of all the functions that have been implemented for the runtime file browser.

Any assistance would be appreciated with what I did in webgl.

Please take a look at the jslib plugin that is included.

    UploadFile: function(gameObjectNamePtr, methodNamePtr, filterPtr, multiselect) {
        gameObjectName = Pointer_stringify(gameObjectNamePtr);
        methodName = Pointer_stringify(methodNamePtr);
        filter = Pointer_stringify(filterPtr);

        // Delete if element exist
        var fileInput = document.getElementById(gameObjectName)
        if (fileInput) {
            document.body.removeChild(fileInput);
        }

        fileInput = document.createElement('input');
        fileInput.setAttribute('id', gameObjectName);
        fileInput.setAttribute('type', 'file');
        fileInput.setAttribute('style','display:none;');
        fileInput.setAttribute('style','visibility:hidden;');
        if (multiselect) {
            fileInput.setAttribute('multiple', '');
        }
        if (filter) {
            fileInput.setAttribute('accept', filter);
        }
        fileInput.onclick = function (event) {
            // File dialog opened
            this.value = null;
        };
        fileInput.onchange = function (event) {
            // multiselect works
            var urls = [];
            for (var i = 0; i < event.target.files.length; i++) {
                urls.push(URL.createObjectURL(event.target.files[i]));
            }
            // File selected
            SendMessage(gameObjectName, methodName, urls.join());

            // Remove after file selected
            document.body.removeChild(fileInput);
        }
        document.body.appendChild(fileInput);

        document.onmouseup = function() {
            fileInput.click();
            document.onmouseup = null;
        }
    },
};
mergeInto(LibraryManager.library, StandaloneFileBrowserWebGLPlugin);

**Comment by mlavik1** [comment]
Hi! And sorry for the late reply.

I'm afraid I'm not the best candidate to help you, since javascript and web development isn't something I have much experience with.
Maybe you could try asking on Unity Answers: https://answers.unity.com/index.html
Or on the Unity Forums: https://forum.unity.com/
To make it easier for people to help you, maybe add some more context/description, and maybe create a minimal test project where you simply try to upload a file (without volume rendering or anything), that you can share with them.

**Comment by Karthikarc115** [comment]
> Hi! And sorry for the late reply.
> 
> I'm afraid I'm not the best candidate to help you, since javascript and web development isn't something I have much experience with. Maybe you could try asking on Unity Answers: https://answers.unity.com/index.html Or on the Unity Forums: https://forum.unity.com/ To make it easier for people to help you, maybe add some more context/description, and maybe create a minimal test project where you simply try to upload a file (without volume rendering or anything), that you can share with them.
> 
> Or would it be an alternative to [download](https://docs.unity3d.com/ScriptReference/WWW.html) the datasets from somewhere instead? (such as Dropbox). That might be easier to implement.

okay thank you for the update
