### ISSUE TITLE
error CS1069: The type name 'Color' could not be found in the namespace 'System.Drawing'.

### ISSUE THREAD

**Issue by Meruja** [mlavik1/UnityVolumeRendering#159]
I have downloaded the latest version(1.4) of easy volume renderer and imported it into the project. I came across the below error:

Unity version:  220.3.33f1

Assets\EasyVolumeRendering\Assets\3rdparty\Nifti.NET\NiftiFile.cs(590,24): error CS1069: The type name 'Color' could not be found in the namespace 'System.Drawing'. This type has been forwarded to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

Should I manually install this library?

**Comment by SitronX** [comment]
Just to add to this, this also happened to me when i switched project to UWP platform. On other platforms like standalone and android it is working fine. UWP has some issues with this Color type.

**Comment by mlavik1** [comment]
Actually I was just contacted by someone else who has this issue.
Thanks for the clue @SitronX !
I'll probably just modify the Nifti importer to use something else (Unity's Color struct maybe). Will see if I can get this fixed tonight or tomorrow :)

**Comment by mlavik1** [comment]
@Meruja can you try out this PR to see if that fixes the issue for you? https://github.com/mlavik1/UnityVolumeRendering/pull/160

branch: nifti-colour-fix

**Comment by mlavik1** [comment]
Merged, so you can try it out in master branch.

**Comment by Meruja** [comment]
@mlavik1 It fixed the error, but the volume rendering tab is missing;

Steps:

- Create a project.
- Switch the platform to uwp.
- Import features using MRFT.
      - Mixed Reality Toolkit Extension
      - Mixed Reality OpenXR Plugin
      - WLT Core
- Restart unity.
- Apply the recommended settings for MRTK.
- Import Easy Volume Renderer. And Error appears. Apply the changes mentioned in the PR(160). Errors are fixed, but could not see the "volume rendering" tab.

**Comment by Meruja** [comment]
@mlavik1 It fixes the issue
