### ISSUE TITLE
Sphere cutout

### ISSUE THREAD

**Issue by SitronX** [mlavik1/UnityVolumeRendering#165]
Hello @mlavik1,
some time ago i had a discussion with people in the field, and they said that sphere cutout would work better for them instead of box cutout that is already present here. 

I have already made sphere cutout variant in my project. The implementation is quite similar to your box cutout. Would you be interested if i also tried to add it here? I guess some people might find it handy. There would be basically three options: plane, box and sphere cutouts.

Here is a little showcase. 

https://user-images.githubusercontent.com/68167377/227605118-06530260-c8e9-4fc4-92e6-98bdb7441d00.mp4

**Comment by mlavik1** [comment]
Hi @SitronX ,
That's a great idea!I never thought about that..
So yes please! I would very much appreciate a PR for that :)

By the way, may I ask what kind of project this is? (or is it confidential maybe?) I'm just curious about what people are using the plugin for :grin:

**Comment by SitronX** [comment]
@mlavik1 
Great! I will try to add it in upcoming week/weeks. [This](https://github.com/SitronX/FnO-Hololens2-visualisation) is the project if you are interested to check it out, it is connected with [FnO](https://www.fno.cz/) hospital. Your library turned out to be invaluable resource with this project :)

**Comment by mlavik1** [comment]
Wow, that project looks really interesting!
Really excited to see such a project using this plugin :D

And sorry for the late reply btw. Just been going through another round of cold/flu/COVID or something haha

**Comment by SitronX** [comment]
Hi @mlavik1,
> Wow, that project looks really interesting!

Thanks :)

>And sorry for the late reply btw. Just been going through another round of cold/flu/COVID or something haha

Sure, no worries.

Here is the PR for the sphere cutout. After you return home :D

**Comment by mlavik1** [comment]
Thanks a lot @SitronX !
And sorry for the late reply. I just got back home from holiday :) 
Will have a look at the PR today or tomorrow. Speak to you soon!
