### ISSUE TITLE
Arbitrary shapes for slicing planes

### ISSUE THREAD

**Issue by fdorothy** [mlavik1/UnityVolumeRendering#167]
I'm getting some unexpected results when using non-plane meshes (see attached image) for slicing planes. I'm trying to use a shape that looks like an ultrasound's fov for the slicing plane, and it slices, but it looks like something's inverted with the transformation matrices.

I noticed that in SliceRenderingShader we are using the UV coordinates of the plane. Maybe that assumes a specific planar shape and not an arbitrary shape?

Thanks for this great package!

![ultrasound_fov](https://user-images.githubusercontent.com/999829/228554351-c7f34335-41bf-4f97-a1bc-6b71211be8ba.png)

**Comment by fdorothy** [comment]
I was able to flip and mirror the UV coordinates of my custom mesh, and after a lot of trial and error I was able to get the slicing plane to align up with the rendered volume. Problem solved!

**Comment by mlavik1** [comment]
Glad you could solve the issue!
I should probably have another look at that shader sometime. Using the UV coordinates like that is probably not the most ideal solution.
