### ISSUE TITLE
Can't save imported dataset to prefab => material is missing

### ISSUE THREAD

**Issue by mlavik1** [mlavik1/UnityVolumeRendering#171]
If you try to save an imported dataset as a prefab, the material will not be saved.
I suppose this is because runtime-instantiated materials live in the scene, and references to it outside of the scene will be lost.

**Solution:** We currently have a material prefab for all volumetric datasets, that we create a copy of on load. We don't really need this. Instead, reference the shader by name and create the material on demand (on Start/OnInvalidate?)
Alternatively we kan keep it mostly as it is today, but just re-create the material if it's missing.

**Comment by capgemini-labs** [comment]
Any solution on this issue? I would like to save the instanced gameObject to project

**Comment by mlavik1** [comment]
I'll have a look at it tonight. I think it should be a quick fix :)

**Comment by mlavik1** [comment]
Ok, turns out to be a slightly more complex issue..
However, if you need something urgently you could try out this fix: https://github.com/mlavik1/UnityVolumeRendering/pull/182

It does have one issue though: if you modify anything on the dataset's inspector in the Unity Editor, you might get poor performance when you're doing it.

**Comment by mlavik1** [comment]
You can now save datasets as assets either by:

A: Adding .raw/.nrrd/.nifti dataset to the Assets folder => Will automatically import (**Unity 2021.2+**)

![image](https://user-images.githubusercontent.com/6906872/236404291-d44e69b2-4b8b-4c58-9521-ea5b10878764.png)

OR

B: Right click in folder, select "Volume Rendering" and "Import dataset".

![image](https://user-images.githubusercontent.com/6906872/236404455-244d857a-6350-4d76-b6d2-a2274ed91bdd.png)

To spawn the dataset you can simply drag it into the scene view or scene hierarchy (**Unity 2020.2+**), or spawn it from code (using the `VolumeObjectFactory`).
