### ISSUE TITLE
Nifti file Uploading

### ISSUE THREAD

**Issue by Karthikarc115** [mlavik1/UnityVolumeRendering#188]
Hai Matias

I receive an error while attempting to upload a nifti file from a runtime GUI script, yet I am able to successfully upload the same file via the nifti upload option in the Unity editor. 

Please look at the code that I've sent and the issue that I received.

![Nifti](https://github.com/mlavik1/UnityVolumeRendering/assets/99883381/9dbfa358-a847-4608-a196-0b2fd0e680ea)
![Nifti error](https://github.com/mlavik1/UnityVolumeRendering/assets/99883381/793f2edf-82b7-4ac0-bb6f-7f6eefae2fe4)
![nifti import](https://github.com/mlavik1/UnityVolumeRendering/assets/99883381/b18a166c-f04e-45f8-80ca-78dcd4500cfb)

**Comment by mlavik1** [comment]
Hi!
You need to use `ShowOpenFileDialog` instead of `ShowOpenDirectoryDialog`, then it should work :)
I've made a PR here: #189

**Comment by Karthikarc115** [comment]
ok will try
