### ISSUE TITLE
Help: Slider controller to rendered volume object

### ISSUE THREAD

**Issue by Meruja** [mlavik1/UnityVolumeRendering#193]
I am working on implementing a slider controller to modify the rendered volume object with a new one from a specified folder. Instead of a value, is there a way to show text value in the controller to select?

**Comment by mlavik1** [comment]
Hi again!
Hmm, I'm not sure if I understand exactly what you want to do.

> is there a way to show text value in the controller to select?

Could you elaborate a bit on what you mean here?

However, importing a new dataset while a user drags a slider would probably be very slow, since importing takes time. Could it be an option to import all these datasets into the editor and saving them as prefabs? And then making a script that has a `List` of `VolumeDataset` references (to these prefabs) that you spawn on demand - or maybe you could even just change the `VolumeRenderedObject.dataset` of an existing object. 

I recently added support for saving imported datasets as prefabs. See this: https://github.com/mlavik1/UnityVolumeRendering/pull/183

**Comment by Meruja** [comment]
I am working on implementing a slider controller to modify the rendered volume object with a new one from a specified folder. Currently, the code is set up to read raw files from the designated source directory without any errors and when I move the slider, the new volume object is rendered but the transforms were not reflected properly. Could you please help me to determine the root cause of the issue and implement the necessary modifications to ensure that the new volume object is rendered successfully with the previous objects' transform when the slider is moved?

`

        private void OnOpenRAWDatasetResult(string filePath)
        {
            existingObject = GameObject.FindGameObjectWithTag("VolumeObject");
            //Read the position of existing volume object's position
            objectPosition = existingObject.transform;
            // Get the scale from the volume object
            Vector3 volumeScale = existingObject.transform.localScale;
            // Get the tag from the volume object
            string volumeTag = existingObject.tag;
            // Get the rotation from the existing object
            Vector3 existingEulerAngles = existingObject.transform.eulerAngles;

            // We'll only allow one dataset at a time in the runtime GUI (for simplicity)
            DespawnAllDatasets();

            // Import the dataset
            RawDatasetImporter importer = new RawDatasetImporter(filePath, dimX, dimY, dimZ, dataFormat, endianness, bytesToSkip);
            VolumeDataset dataset = importer.Import();

            // Spawn the object
            if (dataset != null)
            {
                VolumeRenderedObject obj = VolumeObjectFactory.CreateObject(dataset);
                obj.tag = volumeTag;
                obj.transform.position = objectPosition.position;
                // Assign the scale to the target object
                obj.transform.localScale = volumeScale;
                // Assign the rotation to the target object
                obj.transform.eulerAngles = existingEulerAngles;
            }

        }`

**Comment by mlavik1** [comment]
Hmm.. The code above looks fine to me. Exactly how are the "transforms not reflected properly"? Is the scale wrong, or something?
Do you have a project I can test with some datasets, or are they proprietary/closed maybe?

Another thought: Are the dimensions of all these datasets the same? If they are not, you might need to calculate a different scale. By default the RAW dataset importer will set the scale to (1,1,1). This will often not be correct though.. If the pixel spacing is the same for each axis, setting the scale to `new Vector3(dimX, dimY, dimZ) / Mathf.Max(dimX, dimY, dimZ)` or something might work better.

**Comment by Meruja** [comment]
I figured out that the issue was on the data. The dimensions of the data are same. The problem here is initially I import a raw data and then using a slider option I am trying to replace it with another raw file which is edited (Original raw file is opened in 3D slicer and applied simple ITK smooth function) and exported as raw file. 
Here is the reference how the edited image looks in slicer and unity.
#
![CD2FFB62-2D9D-43D2-808D-54793E1949B9](https://github.com/mlavik1/UnityVolumeRendering/assets/28688743/74d28ac6-c107-4c5f-afe5-6f68f9916fb4)
![EB9C1211-A673-48B1-B7E7-32F168164B8A](https://github.com/mlavik1/UnityVolumeRendering/assets/28688743/b1b654f3-d114-4186-b969-90d4b02af5e8)

**Comment by mlavik1** [comment]
Ok I see, Thanks for sharing! So the edited RAW dataset had a different dimension/size then? Is there anything I can help with then, or should I close the issue?

By the way, are there are any filters that you think would be beneficial to add to this library? I've thought about adding that before, but I don't know the practical use cases well enough tbh. Are you mainly using smoothing filters to reduce noise in the dataset?

**Comment by Meruja** [comment]
No, the edited file has the same dimension. The problem here is: the ElementType = MET_FLOAT is overwritten as ElementType = MET_UCHAR when I try to import the edited .raw image. Is there any place you define those values as I couldn't figure it out?

**Comment by Meruja** [comment]
> Ok I see, Thanks for sharing! So the edited RAW dataset had a different dimension/size then? Is there anything I can help with then, or should I close the issue?
> 
> By the way, are there any filters that you think would be beneficial to add to this library? I've thought about adding that before, but I don't know the practical use cases well enough tbh. Are you mainly using smoothing filters to reduce noise in the dataset?

I tried to implement a Gaussian filter for my study, but due to the complexity of the calculation and hardware restriction, I could not perform it in real time.

**Comment by mlavik1** [comment]
> No, the edited file has the same dimension. The problem here is: the ElementType = MET_FLOAT is overwritten as ElementType = MET_UCHAR when I try to import the edited .raw image. Is there any place you define those values as I couldn't figure it out?

Hmm.. we're still talking about RAW datasets right? The `RawDatasetImporter` does not read headers and doesn't automaticlaly support any specific RAW formats, so you need to configure it to use the correct format etc.
For MET_UCHAR I guess you want to set the `contentFormat` parameter to `DataContentFormat.Uint8`.
