### ISSUE TITLE
Simple bug fix for HistogramTextureGenerator

### ISSUE THREAD

**Issue by kamesa7** [mlavik1/UnityVolumeRendering#196]
code at GenerateHistogramTextureOnGPU
`computeHistogram.SetFloat("ValueRange", (float)(numValues - 1));`
should be
`computeHistogram.SetFloat("ValueRange", (float)(sampleCount - 1));`
With this fix, the histogram can be displayed correctly even for data with a large data range.

**Comment by mlavik1** [comment]
Hi @kamesa7 ,
You're right, thanks a lot for pointing this out!
I'll have a look at it and make a PR soon.
I guess the histogram texture generation could be made async as well now - instead of blocking the main thread while fetching the compute buffer. I'll have a look at that too.

**Comment by mlavik1** [comment]
Fixed! Thanks again for reporting.
