### ISSUE TITLE
How to get or create dataset?

### ISSUE THREAD

**Issue by hont127** [mlavik1/UnityVolumeRendering#2]
I downloaded the DICOM software but couldn't open the preset data set. How can I create or download a data set?

**Comment by hont127** [comment]
Okay,i`m found .dat file create csharp code.

**Comment by mlavik1** [comment]
@hont127 Hi! Sorry for the late reply (I don't check my GitHub so often during the summer). I'm glad you solved it!

Please let me know if you have any other issues, or suggestions/feedback. I'd like to spend some more time on this project after the summer.
