### ISSUE TITLE
Volume render to mesh?

### ISSUE THREAD

**Issue by yusufalibrahim1994** [mlavik1/UnityVolumeRendering#206]
Is there a way to convert the volume render to a mesh?

**Comment by mlavik1** [comment]
Hi @yusufalibrahim1994 

The plugin does not have such a feature at the moment. However, there are other tools that can do this. I would recommend 3D Slicer: https://www.slicer.org/

It allows you to create a segmentation, and export it as .obj (wavefront) or .stl: https://www.youtube.com/watch?v=cMTlLVS4Mlo
