### ISSUE TITLE
"Urgent!!!" Importing Nifti data is not working

### ISSUE THREAD

**Issue by BrightLight1115A** [mlavik1/UnityVolumeRendering#207]
I am making Unity project respected Medical content.
In here, it is necessary to import ."nii" files to the Unity.
So I found this repository out and downloaded.
Raw data is working well, but ".nii" file is not imported as an errors occured.
I attached work video file below.
Please help me to fix these errors.
https://pixeldrain.com/u/8wTJKUc1

**Comment by mlavik1** [comment]
Hi!
Quick question: Have you enabled the [SimpleITK integration](https://github.com/mlavik1/UnityVolumeRendering/blob/master/Documentation/SimpleITK/SimpleITK.md)?
The built-in NIFTI importer is quite basic, but the SimpleITK one has worked better for me.

**Comment by mlavik1** [comment]
Hi, I will close this issue unless there is anything more I can help with.
