### ISSUE TITLE
Help wanted! Slicing in 3D

### ISSUE THREAD

**Issue by Meruja** [mlavik1/UnityVolumeRendering#211]
I'm currently implementing a UI interface for hololens to slice the voluemeObject in 3 dimension. I have tried the cross section but still wonder how to do it in 3 dimension by creating a slider object and slice it. Now I could able to do it for volume asset(Texture) not for volume object.

I am currently working on implementing a UI interface for HoloLens to enable slicing of volume objects in three dimensions. I have already experimented with cross-sections, but I am still exploring how to achieve this functionality by creating a slider object and using it to slice the volume. At the moment, I have successfully implemented this feature for volume assets in the form of textures, but I am still working on adapting it for volume objects.

Here is a snippet of the code I have developed so far for X axis:
Controller=>

`
 public class VolumeRenderingController : MonoBehaviour {

        [SerializeField] protected VolumeRendering volume;
        [SerializeField] protected Slider sliderXMin, sliderXMax, sliderYMin, sliderYMax, sliderZMin, sliderZMax;
        [SerializeField] private VolumeRenderedObject volumeRenderedObject;

        void Start ()
        {
            const float threshold = 0.025f;

            sliderXMin.onValueChanged.AddListener((v) => {
                //volumeRenderedObject = GameObject.FindGameObjectWithTag("VolumeObject").GetComponent<VolumeRenderedObject>();
                volume.sliceXMin = sliderXMin.value = Mathf.Min(v, volume.sliceXMax - threshold);
                volumeRenderedObject.sliceXMin = sliderXMin.value = Mathf.Min(v, volume.sliceXMax - threshold);
            });
            sliderXMax.onValueChanged.AddListener((v) => {
                volume.sliceXMax = sliderXMax.value = Mathf.Max(v, volume.sliceXMin + threshold);
            });
        }`

VolumeRendering=>

`

    [RequireComponent (typeof(MeshRenderer), typeof(MeshFilter))]
    public class VolumeRendering : MonoBehaviour {

        [SerializeField] protected Shader shader;
        protected Material material;
        //[SerializeField]
        //private VolumeRenderedObject volumeRenderedObject;

        [SerializeField] Color color = Color.white;
        [Range(0f, 1f)] public float threshold = 0.5f;
        [Range(0.5f, 5f)] public float intensity = 1.5f;
        [Range(0f, 1f)] public float sliceXMin = 0.0f, sliceXMax = 1.0f;
        [Range(0f, 1f)] public float sliceYMin = 0.0f, sliceYMax = 1.0f;
        [Range(0f, 1f)] public float sliceZMin = 0.0f, sliceZMax = 1.0f;
        public Quaternion axis = Quaternion.identity;

        public Texture volume;

        protected virtual void Start () {
            material = new Material(shader);
            GetComponent<MeshFilter>().sharedMesh = Build();
            GetComponent<MeshRenderer>().sharedMaterial = material;
        }
        
        protected void Update () {
            material.SetTexture("_Volume", volume);
            material.SetColor("_Color", color);
            material.SetFloat("_Threshold", threshold);
            material.SetFloat("_Intensity", intensity);
            material.SetVector("_SliceMin", new Vector3(sliceXMin, sliceYMin, sliceZMin));
            material.SetVector("_SliceMax", new Vector3(sliceXMax, sliceYMax, sliceZMax));
            material.SetMatrix("_AxisRotationMatrix", Matrix4x4.Rotate(axis));
        }

        Mesh Build() {
            var vertices = new Vector3[] {
                new Vector3 (-0.5f, -0.5f, -0.5f),
                new Vector3 ( 0.5f, -0.5f, -0.5f),
                new Vector3 ( 0.5f,  0.5f, -0.5f),
                new Vector3 (-0.5f,  0.5f, -0.5f),
                new Vector3 (-0.5f,  0.5f,  0.5f),
                new Vector3 ( 0.5f,  0.5f,  0.5f),
                new Vector3 ( 0.5f, -0.5f,  0.5f),
                new Vector3 (-0.5f, -0.5f,  0.5f),
            };
            var triangles = new int[] {
                0, 2, 1,
                0, 3, 2,
                2, 3, 4,
                2, 4, 5,
                1, 2, 5,
                1, 5, 6,
                0, 7, 4,
                0, 4, 3,
                5, 4, 7,
                5, 7, 6,
                0, 6, 7,
                0, 1, 6
            };

            var mesh = new Mesh();
            mesh.vertices = vertices;
            mesh.triangles = triangles;
            mesh.RecalculateNormals();
            mesh.hideFlags = HideFlags.HideAndDontSave;
            return mesh;
        }

        void OnValidate()
        {
            Constrain(ref sliceXMin, ref sliceXMax);
            Constrain(ref sliceYMin, ref sliceYMax);
            Constrain(ref sliceZMin, ref sliceZMax);
        }

        void Constrain (ref float min, ref float max)
        {
            const float threshold = 0.025f;
            if(min > max - threshold)
            {
                min = max - threshold;
            } else if(max < min + threshold)
            {
                max = min + threshold;
            }
        }

        void OnDestroy()
        {
            Destroy(material);
        }

    }

}

`

Please note that this is an ongoing development, and I am actively working on finding a solution to implement the slicing functionality for volume objects.

**Comment by mlavik1** [comment]
Hi, sorry for the late reply. I was on holiday (still am btw). Did you solve the issue?
Just a note: Instead of implementing slicing from scratch, you could maybe just spawn 3 cross section planes and move them? See https://github.com/mlavik1/UnityVolumeRendering/blob/master/Documentation/General/CrossSectionTools/CrossSectionTools.md

**Comment by Meruja** [comment]
Yeah, I just use 6 cross section plane and moved them. But still, there is an issue. I didn't have any issue with x and y direction, but for z, when I change the position and the rotation f the plane. the volume object is disappear in the play mode(It is visible in scene view and game view). Do You know why?

Is there an option to change the intensity values of the volume object(increase of decrease)?

**Comment by mlavik1** [comment]
Hmm, no.. There's not more than 6 cross section tools enabled, right? (because there's an upper limit of 8).
If you're able to reproduce the issue in a test scene that you can send me, then I could probably have a look at it.

And what do you mean by "intensity values"? Do you mean the density values of the voxels? Those can be accessed from the `data` array in `VolumeDataset.cs`

**Comment by Meruja** [comment]
> Hmm, no.. There's not more than 6 cross section tools enabled, right? (because there's an upper limit of 8). If you're able to reproduce the issue in a test scene that you can send me, then I could probably have a look at it.

No, just 6 are enabled. 

> And what do you mean by "intensity values"? Do you mean the density values of the voxels? Those can be accessed from the `data` array in `VolumeDataset.cs`
Yeah, Can we change those values?

**Comment by mlavik1** [comment]
Hmm then I'm not sure..

And yes, the "data" array can be modified from C#. You can just iterate through the array and change the values as you like (multiply by some number if you wish to change the scale, etc.).
