### ISSUE TITLE
VR UI Interaction issues

### ISSUE THREAD

**Issue by Karthikarc115** [mlavik1/UnityVolumeRendering#212]
Hai Matias,

Could you please let me know if there is a problem with the VR support  because when I tried to use the VR feature using the SteamVR user interface, the controller interaction was not working.

**Comment by mlavik1** [comment]
HI!
There is not automatic VR support in this plugin. I know there are some users who use it in VR, but they had to set that up themselves. You can treat the volume rendered object like a normal mesh in Unity. If you want to interact with it you probably need to add some box collider or something to it. It depends on what plugins you're using for VR interaction :)

**Comment by Karthikarc115** [comment]
> HI! There is not automatic VR support in this plugin. I know there are some users who use it in VR, but they had to set that up themselves. You can treat the volume rendered object like a normal mesh in Unity. If you want to interact with it you probably need to add some box collider or something to it. It depends on what plugins you're using for VR interaction :)

ok thank you will try to do it
