### ISSUE TITLE
Calculate volume size

### ISSUE THREAD

**Issue by yangx789** [mlavik1/UnityVolumeRendering#238]
Hello, I was wondering if it's possible to calculate the imported volume size. Any help will be appreciated.

**Comment by mlavik1** [comment]
You mean the physical size of the dataset? For DICOM and NRRD that should already be taken care of (at least for SimpleITK), however when spawning a dataset the VolumeRenderedObject is scaled down to make sure all datasets have approximately the same visual size. You can disable that by commenting out [this line of code](https://github.com/mlavik1/UnityVolumeRendering/blob/11f1ae94225e1522f8df2202d9940fe01979a345/Assets/Scripts/VolumeObject/VolumeObjectFactory.cs#L75).
Alternatively you can set the scale of the "VolumeRenderedObject" (GameObject) to 1,1,1 after import.


**More detailed explanation:**
For DICOM the scale is calculated [like this](https://github.com/mlavik1/UnityVolumeRendering/blob/11f1ae94225e1522f8df2202d9940fe01979a345/Assets/Scripts/Importing/ImageSequenceImporter/SimpleITK/SimpleITKDICOMImporter.cs#L173), and is applied to the volume container[here](https://github.com/mlavik1/UnityVolumeRendering/blob/11f1ae94225e1522f8df2202d9940fe01979a345/Assets/Scripts/VolumeObject/VolumeObjectFactory.cs#L71)

This reminds me: I should probably add a setting to disable this automatic normalisation of the scale..

**Comment by yangx789** [comment]
Thanks for your quick response :)  I commented the maxscale line and it shows volume object to 1, 1, 1 
The scale parameter (vector3) helps a lot with calculating volume size. Thank you!
