### ISSUE TITLE
Implement Slice rendering with HSV

### ISSUE THREAD

**Issue by tao199988** [mlavik1/UnityVolumeRendering#239]
Hello, I was wondering if it's possible to render slices using the HSV (Hue, Saturation, Value) color space? 
Also, I'm curious about how the colors correspond to the values in the dataset during Slice rendering.

Below is the UltraSonic Data which i need to render with HSV, but i kinda confuse with it.
![ultra](https://github.com/mlavik1/UnityVolumeRendering/assets/96710879/7e4069ce-bbcd-4bd1-9965-9fd2be36ba21)

I tried to fill the texture in TransferFunction.cs(Color tfCols[])  with HSV value to implement the HSV render, but it was a disaster.
![image](https://github.com/mlavik1/UnityVolumeRendering/assets/96710879/c71f1f84-5c33-46c9-8016-30e43938cc67)

I hope the render will look like this.
![image](https://github.com/mlavik1/UnityVolumeRendering/assets/96710879/09a0f221-7345-4ae3-81b5-84b05efc0bfc)

**Comment by mlavik1** [comment]
Hi! Sounds interesting :) I didn't think about this, but sounds like a good way to visualise slices.
The slice renderer is currently very basic. It renders each point using the transfer function, which maps density value to an RGB value. What you want, is to map the value to an HSV value instead, right?
Though, from the screenshot you shared, it looks like it only maps it to a *hue* value.

Either way, you could create a new transfer function that does this, simply by mapping density 0.0 to HSV(0, 1, 1) and density 1.0 to HSV(1,1,1) - so for everything between it's HSV(density, 1, 1). And then convert that to RGB using [Color.HSVToRGB](https://docs.unity3d.com/ScriptReference/Color.HSVToRGB.html)
I can send you an example later today.

**Comment by mlavik1** [comment]
This is how you could do it:
```csharp
public void GenerateHSVTexture()
{
    if (texture == null)
        CreateTexture();

    List<TFColourControlPoint> cols = new List<TFColourControlPoint>(colourControlPoints);

    for (int iX = 0; iX < TEXTURE_WIDTH; iX++)
    {
        float t = iX / (float)(TEXTURE_WIDTH - 1);

        for (int iY = 0; iY < TEXTURE_HEIGHT; iY++)
        {
            float hue = t;
            Color pixCol = Color.HSVToRGB(hue, 1.0f, 1.0f);
            tfCols[iX + iY * TEXTURE_WIDTH] = QualitySettings.activeColorSpace == ColorSpace.Linear ? pixCol.linear : pixCol;
        }
    }

    texture.wrapMode = TextureWrapMode.Clamp;
    texture.SetPixels(tfCols);
    texture.Apply();
}
```

However, in your picture density 0.0 is mapped to blue, and 1.0 to red, so to get similar looking results you can do this:
```csharp
public void GenerateHSVTexture()
{
    if (texture == null)
        CreateTexture();

    List<TFColourControlPoint> cols = new List<TFColourControlPoint>(colourControlPoints);

    for (int iX = 0; iX < TEXTURE_WIDTH; iX++)
    {
        float t = iX / (float)(TEXTURE_WIDTH - 1);

        for (int iY = 0; iY < TEXTURE_HEIGHT; iY++)
        {
            float BLUE_HUE = 240.0f / 360.0f;
            float hue = Mathf.Lerp(BLUE_HUE, 0.0f, t);
            Color pixCol = Color.HSVToRGB(hue, 1.0f, 1.0f);
            tfCols[iX + iY * TEXTURE_WIDTH] = QualitySettings.activeColorSpace == ColorSpace.Linear ? pixCol.linear : pixCol;
        }
    }

    texture.wrapMode = TextureWrapMode.Clamp;
    texture.SetPixels(tfCols);
    texture.Apply();
}
```
Result:
![图片](https://github.com/mlavik1/UnityVolumeRendering/assets/6906872/92243b28-5a09-4106-920e-4bc380111f64)

And here's the modified TransferFunction.cs, that you can copy into "Assets\Scripts\TransferFunction" to test:
[TransferFunction - 副本.zip](https://github.com/mlavik1/UnityVolumeRendering/files/14886155/TransferFunction.-.zip)

**Comment by tao199988** [comment]
THANKS! It works perfectly!!!!
Result:
![image](https://github.com/mlavik1/UnityVolumeRendering/assets/96710879/6924995b-9306-4b71-a8a9-a537391ff644)

**Comment by mlavik1** [comment]
Great to hear! Have a nice weekend :)
