### ISSUE TITLE
SimpleITKImageFileImporter - SimpleITK.DICOMOrient function is non-functional

### ISSUE THREAD

**Issue by MichaelOvens** [mlavik1/UnityVolumeRendering#241]
See here: https://github.com/mlavik1/UnityVolumeRendering/blob/9fa81ec480f3726576d23611eb3faf6b3a83b233/Assets/Scripts/Importing/ImageFileImporter/SimpleITK/SimpleITKImageFileImporter.cs#L51

The `SimpleITK.DICOMOrient` doesn't modify the input image, it returns a modified image just like `SimpleITK.Cast`. Right now, this line isn't doing anything except perform an unnecessary calculation. This can be verified by changing the input coordinate system from `LPS` to `RPS` and observing that the rendered image does not change.

The line should be removed or changed to `image = SimpleITK.DICOMOrient(image, "LPS");` 

I'm happy to create a PR with the desired change, but I'm not sure whether the preference is to implement the intended functionality or preserve the existing functionality.

**Comment by MichaelOvens** [comment]
I'm happy to create a PR with the desired change, but I'm not sure whether the preference is to implement the intended functionality or preserve the existing functionality.

**Comment by mlavik1** [comment]
Ohh, thank you!!
Really nice catch.
Actually, someone had mentioned to me that the rotation would be wrong on some datasets. So you saved me a lot of work now - this bug would certainly be hard to spot 😅 
Did you have a dataset where the orientation was wrong, until you did this change?

And yes, PR is very welcome! Thank you once more.

**Comment by MichaelOvens** [comment]
Thanks! Yeah, I had a DICOM dataset which had been segmented in Slicer and then exported as an NRRD, and the two volumes imported in different rotations. That didn't seem right to me, so I did some digging and stumbled on this.

Looking at it further, I think that this function could actually replace `ImporterUtilsInternal.ConvertLPSToUnityCoordinateSpace`. Rather than using it to normalise all datasets to LPS and then convert them to Unity's coordinate system after they're imported, we can tell SimpleITK to convert the datasets to Unity's coordinate system for us.

I'll do some more testing and hopefully create a PR today or tomorrow.

**Comment by MichaelOvens** [comment]
I've created a PR here: https://github.com/mlavik1/UnityVolumeRendering/pull/244

**Comment by mlavik1** [comment]
Thanks a lot @MichaelOvens !
I'll see if I can have a look at it tonight, or at least this week. Sorry for the delay, things got quite busy this week :sweat_smile:

**Comment by mlavik1** [comment]
Merged!
Again, thanks a lot for this great PR! 🚀

**Comment by MichaelOvens** [comment]
You're very welcome, glad to be able to give back to the project!
