### ISSUE TITLE
Import 3D radial slices (image sequence)

### ISSUE THREAD

**Issue by yangx789** [mlavik1/UnityVolumeRendering#250]
Hello, I was wondering if the image sequence importer also works for radial slices. Here is an example picture :) Different than parallel slices, the radial slices are taken at different angles. Thank you!

![image](https://github.com/mlavik1/UnityVolumeRendering/assets/93155074/8f90a452-47eb-42fc-b9e4-fe39f077e16a)

**Comment by mlavik1** [comment]
Hi! That's unfortunately not supported..
Do you know if SimpleITK has support for this? Doesn't seem to me like it does, but if it does then it should be easy to support.

**Comment by yangx789** [comment]
Thank you for your reply. I'm not sure if SimpleITK support this. It seems like it is challenging to use radial slices and visualize in 3D even in other scientific visualization software. I'll close this issue for now and will update if I find something in the future.
