### ISSUE TITLE
How to import Nifti as ASYNC

### ISSUE THREAD

**Issue by CelaldoganGunes** [mlavik1/UnityVolumeRendering#251]
Hi.
We are using Hololens 2 and MRTK.
We can use normal import functions to load NIFTI files to Unity. 
It works fine on our computers but when we try to import them inside Hololens, the application crashes.
How can we load NIFTI with async? There is only DICOM example in docs.

**Comment by mlavik1** [comment]
Hi!
You should be able to achieve this using [ImporterFactory.CreateImageFileImporter](https://github.com/mlavik1/UnityVolumeRendering/blob/e663f3537f6d35cd494a2375d6a7e3f25f7ef3c9/Assets/Scripts/Importing/ImporterFactory.cs#L39C42-L39C65)

However, On Hololens it will likely not be able to use SimpleITK and instead fallback to the Nifti.net implementation, which is not as stable..
I don't have a Hololens device, so I'm not able to look into this myself, but if you (or anyone reading this) find a good solution then feel free to share here! :) 

I'm not familiar with Hololens, but AFAIK it runs Windows so it should be able to use the same SimpleITK DLLs there as on Windows? If so, that should maybe just be a matter of modifying  [SimpleITKManager.EnableSITK](https://github.com/mlavik1/UnityVolumeRendering/blob/e663f3537f6d35cd494a2375d6a7e3f25f7ef3c9/Assets/Editor/SimpleITK/SimpleITKManager.cs#L28C28-L28C38)
