### ISSUE TITLE
creating .dat files

### ISSUE THREAD

**Issue by arju2020** [mlavik1/UnityVolumeRendering#3]
HI. The two example files of hand and manix in the DataFiles folder works fine. How to create our own ,dat files from CT, MRI, or ultrasound. Thanks,

**Comment by mlavik1** [comment]
Hi.
.dat files are simply datasets in "raw" format.
Most datasets I have seen from CT scans are either in DICOM format or in in a "raw" data format. In the latter case, the file will simply contain all the sample values. To import it, you will need to know the dimension, header size (bytes to skip) and data format.
This is the data you can input here:
![image](https://user-images.githubusercontent.com/6906872/72735365-faaf8d00-3b9b-11ea-805b-8196e8ea7b47.png)

**Comment by mlavik1** [comment]
By the way, I just got another similar question.
I have made a few improvements in the code, and also decided to write a description for: A: How to create import your own raw datasets - B: How to create your own importer (for your own format).
See: https://github.com/mlavik1/UnityVolumeRendering/issues/4
