### ISSUE TITLE
Make a cutout box

### ISSUE THREAD

**Issue by mlavik1** [mlavik1/UnityVolumeRendering#32]
Feature suggestion: Make a cutout box, that hides everything inside the box.
See discussion in #29 

**Requirements:**
- It should be implemented as "#multi_compile" feature, to make sure it doesn't affect performance when disabled.
- You should be able to resize the box.
- It should be possible to see the bounds of the box in the editor, when it is selected.

It's probably best to use a MeshRenderer with a transparent material. That way, it should be highlighted when selected.

If you want to help out: see the code for the CrossSectionPlaneas an example.

**Comment by frere97** [comment]
hey mlavik, this cutout box is just render the parts of the object that are inside the box? or i just get it wrong?

**Comment by frere97** [comment]
hey man, are u working in this feature already? if you are i want to help you

**Comment by mlavik1** [comment]
Hi @frere97 
I haven't started working on this yet, so if you want you are welcome to work on this! 😃

**Comment by frere97** [comment]
i've almost got it, but i faced a problem that's already exists in the project, when youre looking at the wrong face of the cross section plane the object get's extremely buggy, whell you will always be looking at the wrng face if all the faces point to the midle of the object, u know a way to avoid that?

**Comment by mlavik1** [comment]
Ah yes, you are talking about this issue, right?
![image](https://user-images.githubusercontent.com/6906872/101876398-a256f480-3b8c-11eb-9820-13a8c0799c83.png)
I will take a look at it. It's probably a mistake in the shader somewhere.

By the way, how are you implementing the cutout box? I don't think your implementation should be affected by this bug?
What I had in mind was this: You spawn a box that uses a special shader (outline, maybe?), and its matrix is passed to the volume rendering shader. Then, in the shader we check if we are inside the box (transform to world space to the box' local space) and ignore the current point if that's the case.

**Comment by frere97** [comment]
i´ve was trying to make like we have 6 slicing plane at once (it´s not working XD)

**Comment by mlavik1** [comment]
@frere97 aah, I see! Well, that could probably work, but I think it's maybe a bit too expensive 😅   (since you would have to check each of them in the shader). I think using a matrix for the whole box is the best approach in this case.

But I'm glad you found this bug with the slice renderer! That's a terrible bug xD
I'll see if I get time to look at it tomorrow :)

**Comment by frere97** [comment]
okay, i will check this, thank u

**Comment by mlavik1** [comment]
Done in PR #45
