### ISSUE TITLE
Intersection between the volume and other meshes

### ISSUE THREAD

**Issue by denistribouillois** [mlavik1/UnityVolumeRendering#5]
Hello,
I'm using your project to render 3D medical images (and visualize them in VR) and it's working great, thanks for sharing.
But, as you can see in the image below, if the volume intersect another mesh, the rendering order is wrong.

![DepthIssue](https://user-images.githubusercontent.com/7714364/73373596-2ed02f80-42b9-11ea-8dcf-1b1b075099eb.png)

I've try to change the shader code to fix it but with no luck yet.
Based on this thread
https://stackoverflow.com/questions/45475564/how-to-manipulate-depth-value-to-correct-it-in-volume-rendering
the idea would be to stop the ray if the current position of the vertex is further than the depth buffer of the camera. I've try several approaches but none of them worked with your implementation.
Could you have a look?
Other usefull ressources:
https://flafla2.github.io/2016/10/01/raymarching.html#interacting-with-mesh-based-objects
https://www.iquilezles.org/www/articles/raypolys/raypolys.htm

Also if you're interested, I implemented a slicer (3D quad), that can slice the volume in any direction, I can make a Pull Request.
Cheers,
Denis

**Comment by mlavik1** [comment]
Thanks for reporting!
Actually I had never tested this until now, but now that I think of it I haven't done anything to make this work yet.. I'll take a look at it this week! (starting right now)
The volume is rendered as a (face culled) box, so intersections don't look right at the moment.

And regarding the slicer you implemented: I already have a slice renderer, but it can't cut/slice the dataset. So yes, feel free to share the code if you don't mind :) 
I'm planning to have one plane that can both cut/slice the model and also be used as a slice renderer (if that makes sense)? So if you make a pull request I might do some modifications first.

Thank you!

**Comment by mlavik1** [comment]
@denistribouillois Hi again!
I have started working on this now.
I will do some more work before I merge it into master, but the work-in-progress is in this branch: https://github.com/mlavik1/UnityVolumeRendering/tree/depthwrite

I ended up writing the depth in the fragment shader. I simply calculate it from the world position (o0f the last contributing sample along the ray) and multiply it with the MVP matrix. This should also allow intersections between multiple datasets - though you can currently only load one dataset at a time (which is the next thing I'll fix!)

Results:
![image](https://user-images.githubusercontent.com/6906872/73563511-c3739280-445d-11ea-9cfb-c6beb3f4fd74.png)

![image](https://user-images.githubusercontent.com/6906872/73563847-9a9fcd00-445e-11ea-80c5-6500a23541b5.png)

**Comment by denistribouillois** [comment]
Hi, it seems to work as expected! Thanks a lot.
I'm using another pipeline to load the data (I'm only using the shader/material with an existing 3D Texture) and I can confirm that the intersection with multiple volumes seems to behave as expected as well.
Thanks again!

**Comment by mlavik1** [comment]
Thanks a lot for testing!
I just upedated the branch with a change that makes it work with OpenGL as well. Also moved the depth value calculation into a separate function.
I'll clean this up and merge it into master soon.

**Comment by mlavik1** [comment]
And it's done!
Everything is in master now.
Note: I have updated the sample data sets. I replaced them with two new data sets (that have a license allowing me to redistribute them). "VisMale.raw" is the best of them. I'll add more later.

**Comment by denistribouillois** [comment]
Thank's a lot!
I made a pull request to fix a bug on a wrong behaviour at the edges of the volume.
Working like a charm now!

**Comment by mlavik1** [comment]
Thanks for the pull request! :)

**Comment by denistribouillois** [comment]
Closing the issue, since it's now working as expected.
