### ISSUE TITLE
Other samples of volume data

### ISSUE THREAD

**Issue by fmatulic** [mlavik1/UnityVolumeRendering#50]
Hi, great package. Thanks for sharing it.

I was wondering if you could either include or point to some more samples and datasets on the web that can be opened out of the box with your tool.

Cheers

**Comment by mlavik1** [comment]
or DICOM, I have used this archive for testing: https://imaging.nci.nih.gov/nbia-search-cover/
They have a lot of DICOM datasets. Not all of them are 3D scans though.
For the other formats I have come over some dataset collections in past, but I don't remember which ones..

But it would probably be good to make a collection of test datasets that can be used, and put it in a Wiki page on this repository! So I will keep this task open for now :) 
But the NBIA collection is great for DICOM at least.

**Comment by fmatulic** [comment]
That database is a bit overwhelming and requires a special tool do download the images.
I tried some files on this site, but I couldn't open any with your Dicom importer: https://www.aliza-dicom-viewer.com/download/datasets
I'm not familiar with the Dicom format, so not sure what and where I should look for to get proper files that can be imported with your software.

**Comment by mlavik1** [comment]
Thanks a lot for that link!
I will take a look at the models and investigate why they fail. This week is quite busy, but maybe I can find some time on sunday or next week :)

**Comment by mlavik1** [comment]
Closing this now, since the new [SimpleITK integration](https://github.com/mlavik1/UnityVolumeRendering/blob/master/Documentation/SimpleITK.md) adds support for DICOM2000 datasets, and in general all DICOM datasets that SimpleITK can import.
