### ISSUE TITLE
Will this work with VR or MR?

### ISSUE THREAD

**Issue by ljhfdy** [mlavik1/UnityVolumeRendering#51]
Very nice app. I am new in this area, but wondering if I can develop an app (based on this) that can be deployed to a VR headset or a hololens.

Thanks a lot,

**Comment by mlavik1** [comment]
Thank you!
I haven't used it for VR/AR myself (except for a simple test maybe a year ago), but I know some others have, so yes - that should work!
If you get performance issues, you could try decreasing the "NUM_STEPS" constant in the shaders (see https://github.com/mlavik1/UnityVolumeRendering/blob/d495efadc78e1e3fa9ea45e027530adecd34deb2/Assets/Shaders/DirectVolumeRenderingShader.shader#L153)
