### ISSUE TITLE
Memory Leak Identification

### ISSUE THREAD

**Issue by btsai-dev** [mlavik1/UnityVolumeRendering#52]
The repeated usage of Texture2D results in a memory leak as Unity does not release Texture2D objects from memory.

This became an issue when I attempted to use high-resolution datasets. The issue was isolated when the `ImageSetHasUniformDimensions` function in `ImageSequenceImporter` alone would cause an abnormal amount of memory usage.

The issue was fixed by adding `UnityEngine.Object.DestroyImmediate(texture);` whenever the Texture object was no longer needed.

This was tested on Unity 2020.3.7

**Comment by mlavik1** [comment]
Thanks a lot for this info!
If you already have a fix in your own fork, feel free to make a PR. If not I'll make one soon (have been travelling a bit recently, but I'll have more time soon!)

Thanks :slightly_smiling_face:

**Comment by mlavik1** [comment]
Closed by #55  (Thanks again!)
