### ISSUE TITLE
 Easy Volume Renderer doesn't see DICOM files

### ISSUE THREAD

**Issue by IngGabriela** [mlavik1/UnityVolumeRendering#68]
Hey! I am new to unity. I want to use Easy Volume Renderer asset but for some reason, unity doesn't see DICOM files even that I know for sure that they are there. Any suggestions?

**Comment by vahpy** [comment]
You can only select a folder, not file. So it doesn't matter if you can't see the files, click on 'Select folder' and your DICOM files will be added.

**Comment by mlavik1** [comment]
Yes, since this is a 3D viewer we can only import folders of multiple DICOM files (not single files). So as vahpy says, you need to select the folder. Does that work for you now? :)

**Comment by IngGabriela** [comment]
Nop. I have this message

**Comment by IngGabriela** [comment]
Nop. I have this message 
![Untitled](https://user-images.githubusercontent.com/93385314/142413469-ac720f46-4a7e-4a61-9f71-4df1495b2c9e.png)

**Comment by IngGabriela** [comment]
I didn't want to close the subject. Sorry
So, that message appeared and if I press YES I have this error 
![image](https://user-images.githubusercontent.com/93385314/142414021-7331f23f-ca1a-406c-8003-014ad6d56fcd.png)

**Comment by mlavik1** [comment]
Aha, I see the problem now!
This is an issue with the asset store version I made. I'll try to come up with a proper fix for it, but until then, can you copy the file contents of "EasyVolumeRendering/Assets/StreamingAssets" over to a new "StreamingAssets folder in your own project?
Like this:
![image](https://user-images.githubusercontent.com/6906872/142466222-f7d36438-dee7-408e-b93e-93ff3eb1f4a5.png)

**Comment by IngGabriela** [comment]
Hmm, I did this but I received the same error

**Comment by IngGabriela** [comment]
Yes, it works. Thank you! 
BTW, you did an amazing job!

**Comment by mlavik1** [comment]
Great to hear! And thank you very much :) 

I'll keep this issue open until I've done a proper fix for it. Thanks a lot for letting me know!

**Comment by mlavik1** [comment]
I've updated the asset store version now. Again, thanks a lot for reporting this issue to me! 👍
