### ISSUE TITLE
remove texture from memory after destroying the game object

### ISSUE THREAD

**Issue by frere97** [mlavik1/UnityVolumeRendering#73]
does anyone knows if there is a way to remove texture from ram after the gameObject be destroyed?

**Comment by mlavik1** [comment]
I assume it should get garbage collected as soon as it's no longer referenced anywhere.
Does calling [GC.Collect()](https://docs.microsoft.com/en-us/dotnet/api/system.gc.collect?view=net-6.0) help?

Which texture are you talking about, btw? The dataset's main (`VolumeData.dataTexture`) texture?

**Comment by frere97** [comment]
actually i'm trying to figure out XD, i'm starting to think that it is the dataset that is giving me a hard time, if i figure out i will update here

**Comment by mlavik1** [comment]
Thank you! 👍 Good luck researching :D

**Comment by mlavik1** [comment]
Any update on this? Of not I'll close this for now :)

**Comment by frere97** [comment]
Ow, sorry, I'm not working in the project anymore XD


But the texture was being stored in a list in our code, this doesn't happens in yours, sorry, I forgot about this comment

**Comment by mlavik1** [comment]
Ok, thanks for letting me know :) Have a great day!
