### ISSUE TITLE
Problem when moving the scripts to another project

### ISSUE THREAD

**Issue by merinoabel** [mlavik1/UnityVolumeRendering#83]
When merging this project with another one, everything works just fine, but some kind of weird "foggy" filter is applied to all the objects (volumes and UI)  and they appear more opaque. What could this be due to? 
I attach 2 images to show the before and after the transfer of the scripts.
<img width="552" alt="Schermata 2022-01-10 alle 12 47 41" src="https://user-images.githubusercontent.com/38525418/148837318-9b498057-baf3-4ff9-bb38-e7eee0d25634.png">
<img width="557" alt="Schermata 2022-01-10 alle 12 50 03" src="https://user-images.githubusercontent.com/38525418/148837377-9891cfb6-c682-48bb-a0e9-67c9ece58b24.png">

**Comment by vahpy** [comment]
It's unlikely to be an issue caused by this package. Your project may have different settings for brightness or something. Have a look at: Window>Rendering>Lighting>Environment: intensity multiplier for environment lighting and environment reflections

**Comment by mlavik1** [comment]
Yes, it sounds like a project settings related issue. I also noticed that the GUI at the top looks brighter as well?

**Comment by merinoabel** [comment]
Hello, it probably is a settings problem, and i'm sorry for bothering you but i really couldn't find a solution.
And yes, the GUI seems to be affected by the exact same problem. 
Only the slices shown in the slice rendering editor window present the correct brightness, and also any other object that isn't related to the Unity Volume Rendering project (ex: if i add a red ball to the scene it will not be affected by the brightness problem).

@vahpy Thank you for the suggestion, I tried changing those settings but unfortunately it doesn't solve the issue...

**Comment by mlavik1** [comment]
@merinoabel could it be that you're using "Linear" colour space in your project?
Try opening Project settings -> Player -> "Other Settings":
![bilde](https://user-images.githubusercontent.com/6906872/149335980-46efcb25-275f-4565-9a68-6ae3de5ded26.png)

I noticed that I get a similar issue when I change it to linear.

**Comment by mlavik1** [comment]
Glad I could help! Have a nice day too.
